### ISSUE TITLE
ImportError: No module named 'proxmoxer'

### ISSUE THREAD

**Issue by sixteeN11** [ossobv/proxmove#13]
Hi there,

could you please fix this issue?
i need proxmove now and its not working today?

Thank you for doing a great Job!

**Comment by wdoekes** [comment]
```
$ mkvirtualenv proxmove-test --python=`which python3`
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/walter/.virtualenvs/proxmove-test/bin/python3
Also creating executable in /home/walter/.virtualenvs/proxmove-test/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.

$ pip install proxmove
Collecting proxmove
  Using cached https://files.pythonhosted.org/packages/5d/b8/819bc40ad185fc24663e3940314b9c608abb84ab163deeac29f066c40bc6/proxmove-0.1.0.tar.gz
Collecting proxmoxer>=0.2.4 (from proxmove)
Collecting requests>=2.9.1 (from proxmove)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
...

$ proxmove --version
proxmove 0.1.0
```

Works over here..

Did you install the requirements?

https://github.com/ossobv/proxmove/blob/4a6d62f09541d985e4df247f5bf4f2a64fbdf667/setup.py#L43..L46

**Comment by sixteeN11** [comment]
root@v1:~/proxmove# ./proxmove
Traceback (most recent call last):
  File "./proxmove", line 26, in <module>
    from proxmoxer import ProxmoxAPI
ImportError: No module named 'proxmoxer'
root@v1:~/proxmove# apt install proxmoxer
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
E: Paket proxmoxer kann nicht gefunden werden.
root@v1:~/proxmove# pip install proxmoxer
Requirement already satisfied: proxmoxer in /usr/local/lib/python2.7/dist-packages

Nope, sorry.

**Comment by wdoekes** [comment]
```
root@v1:~/proxmove# apt install proxmoxer
```
^-- that package does not exist

```
Requirement already satisfied: proxmoxer in /usr/local/lib/python2.7/dist-packages
```
^-- that is python2, whereas
https://github.com/ossobv/proxmove/blob/master/setup.py#L40
https://github.com/ossobv/proxmove/blob/master/proxmove#L1
^-- that is python3

You'll need to run `pip3 install ...` (after `apt install python3-pip`).

**Comment by wdoekes** [comment]
I think we can close this :-)
