### ISSUE TITLE
Would this work without a Cluster?

### ISSUE THREAD

**Issue by rjsears** [ossobv/proxmove#32]
I just built a new cluster and I want to migrate all of my CTs and VMs over to the cluster from a stand-alone node. This says cluster-to-cluster. Would it work from a single node to a cluster?

Many Thanks!

**Comment by wdoekes** [comment]
Well. If your standalone node has an API, then I see no reason why not.

**Comment by wdoekes** [comment]
> I didn't add any type of API beyond what comes with Proxmox.

Nor did I.

Then I guess you're good to go.

**Comment by rjsears** [comment]
Perfect, I will give it a shot!

**Comment by rjsears** [comment]
Ran into a little problem that I cannot figure out:

`2021-03-10 10:09:00,545: ERROR: missing required binaries ssh and/or zfs and/or mbuffer on storage 'ssdimages'; please install them aborting`

All of those packages are installed on the destination prox node. Is this error saying that they have to be physically located on my zfs:ssdimages drive?

Thanks

**Comment by rjsears** [comment]
OK, making progress. turns out it was a path issue with `mbuffer`. Now when I run it I am getting the following:
`# https://proxmox01:8006/api2/json
  api.nodes("proxmox01/lxc").create(vmid=101, **{'swap': 512, 'ostemplate': 'SRCDISK:vztmpl/ubuntu-14.04-standard_14.04-1_amd64.tar.gz', 'ostype': 'ubuntu', 'cores': 1, 'unprivileged': 1, 'net0': 'name=eth0,bridge=vmbr40,firewall=1,hwaddr=EA:4F:E5:A9:91:05,ip=dhcp,type=veth', 'arch': 'amd64', 'memory': 512, 'rootfs': 'DSTDISK:subvol-101-disk-1,size=20G'})
`

And the following error:
`proxmoxer.core.ResourceException: 500 Internal Server Error: storage 'SRCDISK' does not exist - b'{"data":null}'`

But the container I am attempting to migrate is using an Ubuntu 20.04 template (which is available on both systems) and by looking at the command above it looks like it is looking for a 14.04 template.

**Comment by rjsears** [comment]
So moving on from CT to VMs I am seeing this error:

`ValueError: storage 'SSD_IMAGES' in 'proxmox-old' cluster missing in config`

Yet, it is in my config:
`
[storage:proxmox-old:local@proxmox]
 ssh=root@proxmox
 path=zfs:SSD_IMAGES
 temp=/root/temp
`
And available on the 'sending' system (hostname = proxmox)
![Screen Shot 2021-03-10 at 12 48 13 PM](https://user-images.githubusercontent.com/12837199/110695579-eb741000-819e-11eb-83dc-5804e1cf560e.png)

**Comment by wdoekes** [comment]
I suppose this:
```
[storage:proxmox-old:local@proxmox]
```
should be:
```
[storage:proxmox-old:SSD_IMAGES@proxmox]
```
or:
```
[storage:proxmox-old:SSD_IMAGES]
```

**Comment by wdoekes** [comment]
(I agree that the config syntax is abysmal.)

**Comment by wdoekes** [comment]
As for your LXC ostemplate 14.04 issue:
https://github.com/ossobv/proxmove/blob/9ca7b4c85a00d02493bc17c8e3eb1423afb4930f/proxmove#L422-L424
It is indeed hardcoded, as you can/could see. 

But, we don't use LXC in our Proxmox landscape, so I'm pretty sure migration of those is not (well) implemented.

**Comment by wdoekes** [comment]
(Pro-tip: use the `--debug` flag for more output.)

**Comment by rjsears** [comment]
Thanks for this info, just back from flight rotation, I will take a look at your suggestions and see if I can make it work :-)
