### ISSUE TITLE
Copying to CEPH storage is not possible

### ISSUE THREAD

**Issue by ibr** [ossobv/proxmove#9]

**Comment by wdoekes** [comment]
> No description provided.

I'm sorry, you're not helping you real attractive.

Please try again, bearing in mind that this is an open source project. You may also want to consider the fact that I do not have any ceph storage to test against.

**Comment by lifeboy** [comment]
ceph is very easy to configure and is practically the default in proxmox 7 and can be fully done from the GUI.

I would love to help, but I'm not a dev, so I can't do much more than testing if you were to add this support for ceph.
